spring.application.name=futbol-api-challenge
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:futboldb
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driverClassName=org.h2.Driver

jwt.secret=zv1U4szpjxXrKCYoSfaLfoNtO6TX9h5Iu27nvnrqZ3k
jwt.expiration-ms=36000000
spring.security.user.name=test
spring.security.user.password=12345
spring.security.user.roles=USER

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true