spring.application.name=futbol-api-challenge
spring.h2.console.enabled=true
# Ruta consola h2
spring.h2.console.path=/h2-console
# URL de conexión a la base de datos en memoria llamada 'futboldb'
spring.datasource.url=jdbc:h2:mem:futboldb
# Nombre de usuario para la base de datos
spring.datasource.username=duxchallenge
# Contraseña para la base de datos (puede estar en blanco)
spring.datasource.password=
# Driver de H2
spring.datasource.driverClassName=org.h2.Driver

# JPA Configuration
# Dialecto de Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Permite a Hibernate generar el esquema de la base de datos automáticamente
spring.jpa.hibernate.ddl-auto=update